"""Generate doc-level validation JavaScript from a tree YAML.

The PDF carries no structural radio groups or mutex enforcement — every
checkbox is independent and every text field stands alone. The tree's
logical constraints (select_one mutex, OR-with-multi-select consistency,
when-clauses, mirrored-widget agreement) are checked at save time by JS
embedded as a doc-level pushbutton.

This generator emits a self-contained JavaScript function `validateForm()`
that walks the form, collects issues, and shows a soft warning. The
attorney can dismiss the warning and save anyway — we never block save
since legal forms occasionally need to capture odd structural cases the
tree can't predict.

Naming convention used by `apply_tree.py`:
  * select_one option widget   → "{node_id}__{value}"
  * select_many option widget  → "{node_id}__{value}"
  * enabler widget             → "{node_id}"
  * text/date/currency widget  → "{node_id}" or "{node_id}_{n}"
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

import yaml


def parse_when(when: str) -> tuple[str, list[str], bool, str] | None:
    """Parse a `when:` clause into (gate_id, gate_names, must_be_on, label).

    Supported forms:
      X == 'value'              → gate is checkbox `X__value`, leak if it's off.
      X == true                 → gate is enabler `X`, leak if it's off.
      X == false                → gate is enabler `X`, leak if it's ON.
      X in ['a', 'b', ...]      → gate is any of `X__a`/`X__b`/..., leak if all off.

    Returns None for clauses we can't statically check.
    """
    when = when.strip()
    m_in = re.match(r"\s*([A-Za-z_][A-Za-z0-9_]*)\s+in\s+\[(.+?)\]\s*$", when)
    if m_in:
        gate_id = m_in.group(1)
        vals = re.findall(r"['\"]([^'\"]+)['\"]", m_in.group(2))
        if not vals:
            return None
        names = [f"{gate_id}__{v}" for v in vals]
        label = f"{gate_id} in [{', '.join(repr(v) for v in vals)}]"
        return gate_id, names, True, label
    m_eq = re.match(
        r"\s*([A-Za-z_][A-Za-z0-9_]*)\s*==\s*['\"]?([^'\"\s]+)['\"]?\s*$",
        when,
    )
    if m_eq:
        gate_id, gate_val = m_eq.group(1), m_eq.group(2)
        if gate_val.lower() == "true":
            return gate_id, [gate_id], True, f"{gate_id} is checked"
        if gate_val.lower() == "false":
            return gate_id, [gate_id], False, f"{gate_id} is unchecked"
        return (
            gate_id,
            [f"{gate_id}__{gate_val}"],
            True,
            f"{gate_id}=='{gate_val}'",
        )
    return None


def is_virtual_gate(gate_node: dict | None) -> bool:
    """Gate has no real widgets — leak check would always fire spuriously."""
    if not gate_node:
        return False
    if gate_node.get("virtual"):
        return True
    if gate_node.get("type") == "select_one":
        opts = gate_node.get("options") or []
        if opts and all(
            isinstance(o, dict) and o.get("virtual") for o in opts
        ):
            return True
    return False


JS_HEADER = """\
// Auto-generated by gen_validation_js.py — do not hand-edit.
// Regenerate from tree YAML to update.
function validateForm() {
  var issues = [];

  function isFilled(name) {
    var f = this.getField(name);
    if (!f) return false;
    var v = f.value;
    if (v === null || v === undefined) return false;
    var s = ("" + v).replace(/\\s+/g, "");
    return s.length > 0 && s !== "Off";
  }

  function isChecked(name) {
    var f = this.getField(name);
    if (!f) return false;
    var v = ("" + f.value);
    return v !== "Off" && v !== "" && v !== "null";
  }

  function fieldExists(name) {
    return !!this.getField(name);
  }

"""

JS_FOOTER = """
  if (issues.length === 0) {
    app.alert({
      cMsg: "All checks passed. The form looks consistent.",
      cTitle: "Form Validation",
      nIcon: 3,
      nType: 0
    });
    return true;
  }

  var msg = "The form has " + issues.length + " possible issue(s):\\n\\n"
          + issues.join("\\n\\n")
          + "\\n\\nThese are warnings, not blockers. You can save anyway "
          + "if you intend the form to look this way.";
  app.alert({
    cMsg: msg,
    cTitle: "Form Validation — Issues Found",
    nIcon: 1,
    nType: 0
  });
  return false;
}

// Bind to the button's mouse-up action via /A in the widget annotation.
validateForm();
"""


def _checkbox_names(node: dict) -> list[tuple[str, str]]:
    """Return [(option_value, field_name)] for widget-bearing options."""
    out: list[tuple[str, str]] = []
    for opt in node.get("options") or []:
        if not isinstance(opt, dict) or opt.get("virtual"):
            continue
        val = opt.get("value")
        if val is None:
            continue
        if not (opt.get("widget") or opt.get("widgets")):
            continue
        out.append((val, f"{node['id']}__{val}"))
    return out


def build_when_index(tree: dict) -> dict[tuple[str, str], list[dict]]:
    """Map (gate_id, gate_value) → [dependent_nodes].

    For `X == 'val'`/`X == true`/`X == false` clauses the value key is `val` /
    `"true"` / `"false"` respectively. For `X in [a, b]` clauses, the dependent
    is registered under each member value.
    """
    index: dict[tuple[str, str], list[dict]] = {}
    for node in tree.get("nodes", []):
        if not isinstance(node, dict):
            continue
        parsed = parse_when((node.get("when") or "").strip())
        if not parsed:
            continue
        gate_id, gate_names, must_be_on, _label = parsed
        for gname in gate_names:
            # gate_name is either `gate_id` (boolean enabler) or `gate_id__value`.
            if gname == gate_id:
                key = (gate_id, "true" if must_be_on else "false")
            else:
                key = (gate_id, gname[len(gate_id) + 2:])
            index.setdefault(key, []).append(node)
    return index


def _text_field_names(node: dict) -> list[str]:
    """Return field names for text/date/currency/enabler nodes.

    All widgets of a single node share the same /T (consolidated under a
    parent field by apply_tree), so there's exactly one logical name.
    """
    nid = node.get("id")
    if not nid:
        return []
    return [nid]


def gen_js(tree: dict) -> str:
    nodes_by_id = {
        n.get("id"): n for n in tree.get("nodes", [])
        if isinstance(n, dict) and n.get("id")
    }
    when_index = build_when_index(tree)
    lines: list[str] = []

    for node in tree.get("nodes", []):
        if not isinstance(node, dict):
            continue
        nid = node.get("id")
        ntype = node.get("type")
        if not nid:
            continue

        if ntype == "select_one":
            # Mutex: at most one option's checkbox checked.
            if not node.get("virtual"):
                opts = _checkbox_names(node)
                if len(opts) >= 2:
                    checks = ", ".join(json.dumps(name) for _, name in opts)
                    lines.append(f"  // select_one mutex: {nid}")
                    lines.append(f"  (function() {{")
                    lines.append(f"    var names = [{checks}];")
                    lines.append(f"    var on = [];")
                    lines.append(f"    for (var i = 0; i < names.length; i++) "
                                 f"if (isChecked(names[i])) on.push(names[i]);")
                    lines.append(f"    if (on.length > 1) issues.push("
                                 f"\"More than one option selected for "
                                 f"'{nid}': \" + on.join(\", \"));")
                    lines.append(f"  }})();")
                    lines.append("")

            # Virtual mutex: a virtual select_one's columns shouldn't both fill.
            if node.get("virtual"):
                gated_by_value: dict[str, list[str]] = {}
                for opt in node.get("options") or []:
                    if not isinstance(opt, dict):
                        continue
                    val = opt.get("value")
                    if not val:
                        continue
                    for n2 in when_index.get((nid, val), []):
                        gated_by_value.setdefault(val, []).extend(
                            _text_field_names(n2)
                        )
                if len(gated_by_value) >= 2:
                    vals = sorted(gated_by_value.keys())
                    column_lists = ", ".join(
                        f"{json.dumps(v)}: " + json.dumps(gated_by_value[v])
                        for v in vals
                    )
                    lines.append(f"  // virtual mutex: {nid}")
                    lines.append(f"  (function() {{")
                    lines.append(f"    var cols = {{{column_lists}}};")
                    lines.append(f"    var filled = {{}};")
                    lines.append(f"    for (var v in cols) {{")
                    lines.append(f"      filled[v] = false;")
                    lines.append(f"      for (var i = 0; i < cols[v].length; i++)")
                    lines.append(f"        if (isFilled(cols[v][i])) "
                                 f"{{ filled[v] = true; break; }}")
                    lines.append(f"    }}")
                    lines.append(f"    var n_filled = 0;")
                    lines.append(f"    for (var v in filled) if (filled[v]) n_filled++;")
                    lines.append(f"    if (n_filled > 1) issues.push("
                                 f"\"Multiple alternatives populated for "
                                 f"'{nid}'. Pick one.\");")
                    lines.append(f"  }})();")
                    lines.append("")

            # OR-with-multi-select: one real option + one virtual option,
            # downstream select_many gated by the virtual value contradicts
            # the real option being checked.
            real_opts = [o for o in (node.get("options") or [])
                         if isinstance(o, dict) and not o.get("virtual")
                         and (o.get("widget") or o.get("widgets"))]
            virtual_opts = [o for o in (node.get("options") or [])
                            if isinstance(o, dict) and o.get("virtual")]
            if len(real_opts) == 1 and len(virtual_opts) == 1:
                real_name = f"{nid}__{real_opts[0]['value']}"
                vval = virtual_opts[0]["value"]
                for n2 in when_index.get((nid, vval), []):
                    if n2.get("type") != "select_many" or n2.get("id") == nid:
                        continue
                    party_names = [json.dumps(f"{n2['id']}__{o['value']}")
                                   for o in n2.get("options") or []
                                   if isinstance(o, dict) and o.get("value")]
                    if not party_names:
                        continue
                    lines.append(f"  // OR-with-multi-select: {nid} vs {n2['id']}")
                    lines.append(f"  (function() {{")
                    lines.append(f"    var partyNames = [{', '.join(party_names)}];")
                    lines.append(f"    var anyParty = false;")
                    lines.append(f"    for (var i = 0; i < partyNames.length; i++)")
                    lines.append(f"      if (isChecked(partyNames[i])) "
                                 f"{{ anyParty = true; break; }}")
                    lines.append(f"    if (isChecked({json.dumps(real_name)}) "
                                 f"&& anyParty) issues.push("
                                 f"\"'{real_opts[0]['value']}' is checked but "
                                 f"parties are listed in '{n2['id']}'.\");")
                    lines.append(f"  }})();")
                    lines.append("")

        # ── when-clause leak detection ────────────────────────────────────
        # If a node is gated and the gate is not satisfied, the gated field
        # should not be filled. Soft-warn on leaks. Supports:
        #   X == 'value'   → checkbox X__value must be checked
        #   X == true      → enabler X must be checked
        #   X == false     → enabler X must NOT be checked
        #   X in [a, b]    → any of X__a, X__b must be checked
        when = (node.get("when") or "").strip()
        if when and ntype in ("text", "date", "currency"):
            ref_fields = _text_field_names(node)
            if not ref_fields:
                continue
            parsed = parse_when(when)
            if not parsed:
                continue
            gate_id, gate_names, must_be_on, label = parsed
            if is_virtual_gate(nodes_by_id.get(gate_id)):
                # Virtual gate has no widget — runtime can't tell if it's
                # satisfied. The implicit-column mutex check covers the
                # only case (multiple alt-column fields filled) we can detect.
                continue
            gates_arr = "[" + ", ".join(json.dumps(n) for n in gate_names) + "]"
            ref_list = ", ".join(json.dumps(n) for n in ref_fields)
            polarity = "!any_gate_on" if must_be_on else "any_gate_on"
            msg = json.dumps(
                f"'{nid}' is filled but its gate is not satisfied ({label})."
            )
            lines.append(f"  // when-leak: {nid} gated by {label}")
            lines.append(f"  (function() {{")
            lines.append(f"    var gates = {gates_arr};")
            lines.append(f"    var any_gate_on = false;")
            lines.append(f"    for (var i = 0; i < gates.length; i++) "
                         f"if (isChecked(gates[i])) "
                         f"{{ any_gate_on = true; break; }}")
            lines.append(f"    if ({polarity}) {{")
            lines.append(f"      var refs = [{ref_list}];")
            lines.append(f"      for (var j = 0; j < refs.length; j++) {{")
            lines.append(f"        if (isFilled(refs[j])) {{")
            lines.append(f"          issues.push({msg});")
            lines.append(f"          break;")
            lines.append(f"        }}")
            lines.append(f"      }}")
            lines.append(f"    }}")
            lines.append(f"  }})();")
            lines.append("")

    return JS_HEADER + "\n".join(lines) + JS_FOOTER


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("tree_yaml", type=pathlib.Path)
    ap.add_argument("--out", type=pathlib.Path)
    args = ap.parse_args()
    if not args.tree_yaml.exists():
        print(f"missing: {args.tree_yaml}", file=sys.stderr)
        return 2
    tree = yaml.safe_load(args.tree_yaml.read_text())
    js = gen_js(tree)
    out = args.out or args.tree_yaml.with_suffix(".validate.js")
    out.write_text(js)
    print(f"wrote {out} ({len(js)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
