"""Fill `attorney_bar_number` + `attorney_email` from attorney_name.

Why this exists:
  Qwen rarely emits Maine Bar Number or email when filling attorney
  blocks — neither appears in the source narrative because the case
  generator's PERSON_SCHEMA didn't capture them. Forms with these
  widgets (DE-201/DE-502/DE-504/DE-507/PP-412 ...) then leave them
  blank, and the vision audit flags `blank_required`.

  Values are mock but stable per attorney: same name → same bar# and
  email across all forms and events. Stability lets a panel reader
  correlate fillings on the same attorney without surprise.

  Derivation lives in scripts/backfill_attorney_block.py so case-data
  backfill and per-fill inference produce the same values.

Place in the fix chain: AFTER infer_notary_fields/other inference that
doesn't touch attorney fields; BEFORE recompute_overwrite.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

# Reuse derivation from the case-generator backfill so the two paths
# (case-data backfill vs. per-fill inference) stay byte-identical.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from scripts.backfill_attorney_block import (  # noqa: E402
    derive_bar_number, derive_email, derive_phone,
)


def _get(answers: dict, fid: str) -> str:
    a = answers.get(fid)
    if a is None:
        return ""
    if isinstance(a, dict):
        v = a.get("value")
    else:
        v = a
    if v in (None, "", " "):
        return ""
    return str(v).strip()


def _set(answers: dict, fid: str, value: str, source: str) -> bool:
    if fid not in answers:
        return False
    if _get(answers, fid):
        return False
    a = answers[fid]
    if isinstance(a, dict):
        a["value"] = value
        a["confidence"] = max(float(a.get("confidence") or 0), 0.75)
        a.setdefault("infer_provenance", []).append(
            {"to": value, "method": f"bar-{source}"})
    else:
        answers[fid] = value
    return True


CASES_PATH_DEFAULT = pathlib.Path("router/synthetic_cases.jsonl")


# Stock attorneys for cases that lack an `attorney` party. Names look
# like Maine bar members; bar/email/phone are still derived via
# `derive_*(name)` so they stay self-consistent. Selection is sha256-
# stable per case_id so the same case picks the same attorney across
# forms and re-runs.
STOCK_ATTORNEYS = (
    ("Jonathan P. Mitchell, Esq.",
     "Mitchell Law Office, 142 Main Street, Portland, ME 04101"),
    ("Margaret A. Sullivan, Esq.",
     "Sullivan & Associates, 28 Elm Street, Bangor, ME 04401"),
    ("Robert C. Bouchard, Esq.",
     "Bouchard Law LLC, 71 Federal Street, Augusta, ME 04330"),
    ("Catherine E. Pelletier, Esq.",
     "Pelletier Legal Services, 14 High Street, Lewiston, ME 04240"),
)


def _seeded_stock_attorney(case_id: str) -> tuple[str, str]:
    import hashlib
    h = hashlib.sha256((case_id or "").encode()).digest()
    return STOCK_ATTORNEYS[h[0] % len(STOCK_ATTORNEYS)]


def _lookup_attorney(case_id: str,
                     cases_path: pathlib.Path) -> dict | None:
    """Pull case.parties.attorney from synthetic_cases.jsonl if present.

    Preferred over name-hash derivation because the case data may
    carry a firm-derived email domain that the pure name-hash path
    can't reconstruct.
    """
    if not case_id or not cases_path.exists():
        return None
    for line in cases_path.read_text().splitlines():
        if not line.strip():
            continue
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        case = d.get("case") or {}
        if case.get("case_id") != case_id:
            continue
        atty = (case.get("parties") or {}).get("attorney")
        if isinstance(atty, dict):
            return atty
        return None
    return None


def process(filled: dict, case_id: str | None = None,
            cases_path: pathlib.Path = CASES_PATH_DEFAULT,
            schema_path: pathlib.Path | None = None
            ) -> tuple[dict, list]:
    new_filled = json.loads(json.dumps(filled))
    answers = new_filled.get("answers") or {}
    changes: list[tuple[str, str, str]] = []

    # Pre-create empty answer entries for any attorney_* fields declared
    # in the schema but missing from answers. The canon is generated by
    # Qwen and may predate schema widget injections (DE-505, DE-405,
    # DE-601, PP-601, NC-001 in Phase 16). Without this, _set() bails
    # because the field isn't in answers.
    if schema_path and pathlib.Path(schema_path).exists():
        try:
            schema = json.loads(pathlib.Path(schema_path).read_text())
            ATTY_FIDS = (
                "attorney_name", "attorney_address",
                "attorney_phone", "attorney_phone_number",
                "attorney_bar_number", "attorney_bar_no",
                "attorney_maine_bar_number",
                "attorney_email", "attorney_email_address",
            )
            for f in schema.get("fields") or []:
                fid = f.get("field_id")
                if fid in ATTY_FIDS and fid not in answers:
                    answers[fid] = {"value": "", "confidence": 0,
                                     "infer_provenance": []}
        except (OSError, json.JSONDecodeError):
            pass
    new_filled["answers"] = answers

    # Prefer values from the source case record (firm-derived email
    # domain etc.). Fall back to deterministic name-hash derivation.
    atty_rec = _lookup_attorney(case_id, cases_path) if case_id else None
    case_name = (atty_rec or {}).get("full_name") if atty_rec else None
    case_email = (atty_rec or {}).get("email") if atty_rec else None
    case_phone = (atty_rec or {}).get("phone") if atty_rec else None
    case_addr = (atty_rec or {}).get("address") if atty_rec else None
    case_bar = ((atty_rec or {}).get("attrs") or {}).get("bar_number") \
        if atty_rec else None

    # Attorney name — fill from case record if the widget exists but is
    # blank (Qwen sometimes skips a duplicated attorney block on later
    # pages, e.g. DE-201 p4 notification).
    if case_name:
        for cand in ("attorney_name",):
            if cand in answers and not _get(answers, cand):
                if _set(answers, cand, case_name, "from-case"):
                    changes.append((cand, case_name, "from-case"))

    # Resolve the attorney_name we will use for hash-based derivations.
    attorney_name = _get(answers, "attorney_name") or case_name or ""

    # Stock-attorney fallback: if the form has an attorney_name widget
    # but the case has no attorney party, synthesize a deterministic
    # Maine attorney from STOCK_ATTORNEYS. ~52% of synthetic cases lack
    # the attorney party, which leaves attorney blocks blank across
    # DE-301, DE-504, DE-505, etc. Stable per case_id.
    if (not attorney_name and case_id
            and "attorney_name" in answers
            and not _get(answers, "attorney_name")):
        stock_name, stock_addr = _seeded_stock_attorney(case_id)
        if _set(answers, "attorney_name", stock_name, "stock-fallback"):
            changes.append(("attorney_name", stock_name, "stock-fallback"))
            attorney_name = stock_name
            # Also seed address from the stock record if available.
            if "attorney_address" in answers and not case_addr:
                case_addr = stock_addr

    if not attorney_name:
        return new_filled, changes

    # Attorney address — same-block, fill if widget present and blank.
    if case_addr:
        for cand in ("attorney_address",):
            if cand in answers and not _get(answers, cand):
                if _set(answers, cand, case_addr, "from-case"):
                    changes.append((cand, case_addr, "from-case"))

    # Phone — try `attorney_phone` then `attorney_phone_number`.
    for cand in ("attorney_phone", "attorney_phone_number"):
        if cand in answers and not _get(answers, cand):
            phone = case_phone or derive_phone(attorney_name)
            src = "from-case" if case_phone else "from-name-hash"
            if _set(answers, cand, phone, src):
                changes.append((cand, phone, src))
            break

    # Bar number — different trees wire the field as
    # `attorney_bar_number` (DE-101 family, PP-412) or `attorney_bar_no`
    # (MISC-101, PP-406, AD-011, etc.) or `attorney_maine_bar_number`
    # (DE-509). Try all three.
    for cand in ("attorney_bar_number", "attorney_bar_no",
                 "attorney_maine_bar_number"):
        if cand in answers and not _get(answers, cand):
            bar = case_bar or derive_bar_number(attorney_name)
            src = "from-case" if case_bar else "from-name-hash"
            if _set(answers, cand, bar, src):
                changes.append((cand, bar, src))
            break

    # Email — try `attorney_email` then `attorney_email_address`.
    for cand in ("attorney_email", "attorney_email_address"):
        if cand in answers and not _get(answers, cand):
            email = case_email or derive_email(attorney_name)
            src = "from-case" if case_email else "from-name-hash"
            if _set(answers, cand, email, src):
                changes.append((cand, email, src))
            break

    # Role-prefixed attorney groups (DE-503, PP-408 ...). Each group has
    # its own *_name field; if the role-prefixed name is set, derive
    # bar/email/phone from THAT name. Fall back to `attorney_name`.
    role_groups = [
        ("attorney_for_claimant_name",     "attorney_for_claimant"),
        ("attorney_for_personal_rep_name", "attorney_for_personal_rep"),
        ("claimant_attorney_name",         "claimant_attorney"),
        ("conservator_attorney_name",      "conservator_attorney"),
    ]
    for name_fid, prefix in role_groups:
        role_name = _get(answers, name_fid) or attorney_name
        if not role_name:
            continue
        bar_fid = f"{prefix}_bar_number"
        if bar_fid in answers and not _get(answers, bar_fid):
            bar = derive_bar_number(role_name)
            if _set(answers, bar_fid, bar, "role-name-hash"):
                changes.append((bar_fid, bar, "role-name-hash"))
        email_fid = f"{prefix}_email"
        if email_fid in answers and not _get(answers, email_fid):
            email = derive_email(role_name)
            if _set(answers, email_fid, email, "role-name-hash"):
                changes.append((email_fid, email, "role-name-hash"))
        phone_fid = f"{prefix}_phone"
        if phone_fid in answers and not _get(answers, phone_fid):
            phone = derive_phone(role_name)
            if _set(answers, phone_fid, phone, "role-name-hash"):
                changes.append((phone_fid, phone, "role-name-hash"))

    return new_filled, changes


def _extract_case_id(filled_path: pathlib.Path) -> str:
    return filled_path.parent.name


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--filled", type=pathlib.Path, required=True)
    ap.add_argument("--out", type=pathlib.Path, required=True)
    ap.add_argument("--schema", type=pathlib.Path, default=None)
    ap.add_argument("--event-date", type=str, default=None)
    ap.add_argument("--case-id", type=str, default=None)
    ap.add_argument("--cases-path", type=pathlib.Path,
                    default=CASES_PATH_DEFAULT)
    args = ap.parse_args()

    case_id = args.case_id or _extract_case_id(args.filled)
    filled = json.loads(args.filled.read_text())
    new_filled, changes = process(filled, case_id, args.cases_path,
                                  args.schema)
    args.out.write_text(json.dumps(new_filled, indent=2))
    print(f"infer_attorney_bar: {len(changes)} field(s) populated "
          f"(case={case_id})")
    for fid, val, src in changes:
        print(f"  {fid} -> {val!r} ({src})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
